name: Create and Deploy PDF File to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    env:
      OUTPUT_NAME: "joey-gross"  # Define the custom variable here

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source  

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0

      - name: "Create a folder called output"
        run: |
          mkdir output
          cp resume-stylesheet.css output/resume-stylesheet.css
          cp resume.md output/${{ env.OUTPUT_NAME }}-resume.md

      - name: "Install pandoc and wkhtmltopdf"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.0.1/pandoc-3.0.1-1-amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo apt install ./pandoc-3.0.1-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

      - name: "Convert MD to HTML"
        run: |
          pandoc resume.md -f markdown -t html -c resume-stylesheet.css -s -o output/${{ env.OUTPUT_NAME }}-resume.html

      - name: "Convert HTML to PDF"
        run: "wkhtmltopdf --enable-local-file-access output/${{ env.OUTPUT_NAME }}-resume.html output/${{ env.OUTPUT_NAME }}-resume.pdf"

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4
            

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.actor }}'s Resume
          path: output
